openapi: "3.0.0"
info: 
  title: Tshirt Store API
  description: LCO - a course to create api for ecomm Store
  version: 1.1.0
  contact: 
    email: shubhamhalder0@gmail.com
    url: "https://lco.dev" 

servers: 
  - url: "{protocol}://localhost:4500/api/{version}"
    description: for localhost 
    variables: 
      version: 
        enum:
         - v1
         - v2
        default: v1
      protocol: 
       enum:
        - http 
        - https 
       default: http

components: 
 securitySchemes: 
   cookieAuth:
    type: apiKey
    in: cookie
    name: token
   BearerAuth:
    type: http
    scheme: bearer

paths:
  /dummy:
    get:
      tags:
        - Home
      summary: returns a greet message from servers
      responses: 
        200:
          description: All good success
          content:
            application/json: 
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad Request
        500:
          description: Internal Server Error